steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.flex
      - -t
      - ${_AR_TAG}
      - -t
      - ${_AR_LATEST}
      - .
images:
  - ${_AR_TAG}
  - ${_AR_LATEST}
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s